version: '3.8'

services:
  envoy:
    image: envoyproxy/envoy:v1.25-latest
    volumes:
      - ./config:/config
      - ./scripts:/scripts
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9901:9901"
    command: ["-c", "/config/envoy.yaml", "--service-cluster", "ai-gateway"]
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    depends_on:
      - redis
      - auth-service
    networks:
      - ai-network

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - ai-network

  auth-service:
    image: mockserver/mockserver
    ports:
      - "8081:8080"
    command: -serverPort 8080
    networks:
      - ai-network

  mcp-core:
    image: mockserver/mockserver
    ports:
      - "8000:8000"
    command: -serverPort 8000
    networks:
      - ai-network

volumes:
  redis-data:

networks:
  ai-network:
    driver: bridge