domain: ai-gateway
descriptors:
  - key: remote_address
    rate_limit:
      unit: minute
      requests_per_unit: 100

  - key: path
    value: "/deepseek"
    descriptors:
      - key: api_key
        rate_limit:
          unit: minute
          requests_per_unit: 30

  - key: path
    value: "/external-mcp"
    rate_limit:
      unit: minute
      requests_per_unit: 50